name: test_create_tag_and_branch_on_pr_against_main

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  if_merged:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v3

      - name: Create Pull Request against dev
        uses: peter-evans/create-pull-request@v4
        with:
          base: dev
          branch: '${GITHUB_HEAD_REF}'
