name: test_create_tag_and_branch_on_pr_against_main

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v3

      - name: set env vars
        run: |
          echo "TAG_NAME=${GITHUB_HEAD_REF#release/}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: create prod branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'refs/heads/prod/${{ env.TAG_NAME }}'
          sha: '${{ github.event.pull_request.head.sha }}'

      - name: create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: '${{ env.TAG_NAME }}'
          message: '${{ github.event.pull_request.body }}'
          commit_sha: '${{ env.COMMIT_SHA }}'
