name: test_startswith

on:
  pull_request:
    branches:
      - main

jobs:
  if_not_release_or_hotfix:
    if: ${{ !(startsWith(github.head_ref, 'release/v') || startsWith(github.head_ref, 'hotfix/v')) }}
    runs-on: ubuntu-latest
    steps:
      - name: something
        run: echo "not a release or a hotfix"
