name: test_create_tag_and_branch_on_pr_against_dev

on:
  pull_request:
    branches:
      - dev
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v3

      - name: set up python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: set env vars
        run: |
          echo "TAG_NAME=${GITHUB_HEAD_REF#release/}" >> $GITHUB_ENV

      - name: create prod branch
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          python ./.github/scripts/create_branch.py \
          --repo $GITHUB_REPOSITORY \
          --gh-token ${{ secrets.GITHUB_TOKEN }} \
          --sha ${{ github.event.pull_request.head.sha }} \
          --head-branch $GITHUB_HEAD_REF

      - name: create prod tag
        run: |
          export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
          python ./.github/scripts/create_tag.py \
          --repo $GITHUB_REPOSITORY \
          --gh-token ${{ secrets.GITHUB_TOKEN }} \
          --sha ${{ github.event.pull_request.head.sha }} \
          --head-branch $GITHUB_HEAD_REF
